security:
    # Configuraci칩n de codificadores de contrase침as
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    # Proveedores de usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            stateless: true
            jwt: ~ # Si est치s usando autenticaci칩n JWT
            provider: app_user_provider

    # Control de acceso
    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }