User_Index:
    path: /api/users
    controller: App\Controller\UserController::index
    methods: [GET]

Create_User:
    path: /api/users
    controller: App\Controller\UserController::create
    methods: [POST]

Login:
    path: /api/login
    controller: App\Controller\UserController::login
    methods: [POST]