User_Index:
    path: /api/users
    controller: App\Controller\UserController::index
    methods: [GET]

Create_User:
    path: /api/users/register
    controller: App\Controller\UserController::create
    methods: [POST]

Login:
    path: /api/login
    controller: App\Controller\UserController::login
    methods: [POST]

RenewToken:
    path: /api/renewToken
    controller: App\Controller\UserController::renewToken
    methods: [POST]


##Clientes
getCliente:
    path: /api/clientes
    controller: App\Controller\ClientController::index
    methods: [GET]

createCliente:
    path: /api/clientes
    controller: App\Controller\ClientController::create
    methods: [POST]

updateCliente:
    path: /api/clientes/{id}
    controller: App\Controller\ClientController::update
    methods: [PUT]

deleteCliente:
    path: /api/clientes/{id}
    controller: App\Controller\ClientController::delete
    methods: [DELETE]

## Services
getTypeServices:
    path: /api/type_services
    controller: App\Controller\ServiceTypeController::index
    methods: [GET]

createTypeService:
    path: /api/type_services
    controller: App\Controller\ServiceTypeController::create
    methods: [POST]
